version: '3'

services:
  db:
    image: postgres
  web:
    build: ./app
    image: "zosia_web:${TAG}"
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=zosia16.settings.dev
